//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard_page1
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Other_name { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Birth_place { get; set; }
        public string Citizenship { get; set; }
        public Nullable<bool> Eng_knowledge { get; set; }
        public string Education { get; set; }
        public int Work_experience_d { get; set; }
        public int Work_experience_m { get; set; }
        public Nullable<int> Work_experience_y { get; set; }
        public string Passport_number { get; set; }
        public System.DateTime Issue_date { get; set; }
        public string Residing_place { get; set; }
        public string Phone_number { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
    }
}
