//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard_page7
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public string award_name { get; set; }
        public System.DateTime issue_date { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
    }
}
