//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard_page3
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public System.DateTime date { get; set; }
        public string structural_division_name { get; set; }
        public Nullable<int> structural_division_id { get; set; }
        public string post { get; set; }
        public decimal salary { get; set; }
        public string cause { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
        public virtual Structural_divisions Structural_divisions { get; set; }
    }
}
