//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard_page4
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public string qualification_category { get; set; }
        public decimal surcharge_amount { get; set; }
        public string cause { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
    }
}
