//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard_page5
    {
        public int id { get; set; }
        public string employee_code { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string prof_dev_type { get; set; }
        public string educational_institution_name { get; set; }
        public string cause { get; set; }
    
        public virtual EmployeeCard EmployeeCard { get; set; }
    }
}
