//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeCard()
        {
            this.EmployeeCard_page1 = new HashSet<EmployeeCard_page1>();
            this.EmployeeCard_page10 = new HashSet<EmployeeCard_page10>();
            this.EmployeeCard_page3 = new HashSet<EmployeeCard_page3>();
            this.EmployeeCard_page4 = new HashSet<EmployeeCard_page4>();
            this.EmployeeCard_page5 = new HashSet<EmployeeCard_page5>();
            this.EmployeeCard_page6 = new HashSet<EmployeeCard_page6>();
            this.EmployeeCard_page7 = new HashSet<EmployeeCard_page7>();
            this.EmployeeCard_page8 = new HashSet<EmployeeCard_page8>();
            this.EmployeeCard_page9 = new HashSet<EmployeeCard_page9>();
        }
    
        public int id { get; set; }
        public string employee_code { get; set; }
        public string Last_name { get; set; }
        public string First_name { get; set; }
        public string Other_name { get; set; }
        public System.DateTime Birth_date { get; set; }
        public string Post { get; set; }
        public int Work_experience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page1> EmployeeCard_page1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page10> EmployeeCard_page10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page3> EmployeeCard_page3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page4> EmployeeCard_page4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page5> EmployeeCard_page5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page6> EmployeeCard_page6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page7> EmployeeCard_page7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page8> EmployeeCard_page8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeCard_page9> EmployeeCard_page9 { get; set; }
    }
}
