//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_vacancy
    {
        public int vacansy_id { get; set; }
        public string structural_division_name { get; set; }
        public int structural_division_id { get; set; }
        public string post { get; set; }
        public int places_quantity { get; set; }
        public decimal total_per_month { get; set; }
        public string comment { get; set; }
    
        public virtual Structural_divisions Structural_divisions { get; set; }
    }
}
