//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HumanResDBEntities : DbContext
    {
        public HumanResDBEntities()
            : base("name=HumanResDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeCard> EmployeeCard { get; set; }
        public virtual DbSet<Job_vacancy> Job_vacancy { get; set; }
        public virtual DbSet<Staffing_table> Staffing_table { get; set; }
        public virtual DbSet<Structural_divisions> Structural_divisions { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<EmployeeCard_page1> EmployeeCard_page1 { get; set; }
        public virtual DbSet<EmployeeCard_page10> EmployeeCard_page10 { get; set; }
        public virtual DbSet<EmployeeCard_page3> EmployeeCard_page3 { get; set; }
        public virtual DbSet<EmployeeCard_page4> EmployeeCard_page4 { get; set; }
        public virtual DbSet<EmployeeCard_page5> EmployeeCard_page5 { get; set; }
        public virtual DbSet<EmployeeCard_page6> EmployeeCard_page6 { get; set; }
        public virtual DbSet<EmployeeCard_page7> EmployeeCard_page7 { get; set; }
        public virtual DbSet<EmployeeCard_page8> EmployeeCard_page8 { get; set; }
        public virtual DbSet<EmployeeCard_page9> EmployeeCard_page9 { get; set; }
    }
}
