//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHR.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffing_table
    {
        public int staffing_table_id { get; set; }
        public string structural_division_name { get; set; }
        public int structural_division_id { get; set; }
        public string post { get; set; }
        public int number_of_employees { get; set; }
        public decimal tariff_rate { get; set; }
        public Nullable<decimal> allowance { get; set; }
        public decimal total_per_month { get; set; }
        public System.DateTime compilation_date { get; set; }
        public string comment { get; set; }
    
        public virtual Structural_divisions Structural_divisions { get; set; }
    }
}
